### ISSUE TITLE
Update cookie data

### ISSUE THREAD

**Issue by thiagomagro** [etherCorps/SK-Redis-SessionManager#1]
Whats the recommended way to update the data inside the cookie?
Should we just create a new one with the updated data?

Thanks!

**Comment by theetherGit** [comment]
For now you can assign new cookie  to user but we can in introduce in method to update data.
Code for update method:
async const updateCookieData = (key, data) => {
// check for key in redis if exist update the data and then update cookies.
}

**Comment by theetherGit** [comment]
I have added updateCookieData method so now you can use it for update data in redis.
Check examples: routes/api/updateCookieData for more.
