### ISSUE TITLE
`getSession` is currently broken

### ISSUE THREAD

**Issue by hallowatcher** [etherCorps/SK-Redis-SessionManager#3]
https://github.com/etherCorps/SK-Redis-SessionManager/blob/e28b5ca531c403b58d4ecd5a0cb535917065563c/src/lib/providers/ioredis.ts#L113

I believe this line of code need to be:

```typescript
const sessionData = await this.redisClient.get(sessionId);
```

since the sessionId is already stored with the colon in redis:

![image](https://github.com/etherCorps/SK-Redis-SessionManager/assets/6265839/259ddeda-957f-4086-a60d-392ac2114c30)

Another option is to store the key without the left part of the colon: `ghrVLf9Ge1ZSjo4ZtiVO4plA0Q47U5N7CFXF` in that example.

Otherwise it will try to find `sk_ioredis_session:sk_ioredis_session:ghrVLf9Ge1ZSjo4ZtiVO4plA0Q47U5N7CFXF`, which it can't:

![image](https://github.com/etherCorps/SK-Redis-SessionManager/assets/6265839/23954c61-824f-42fc-a2f1-77ca553523ec)

I'm currently on version `1.0.3`.

PS also check the other providers and functions

**Comment by theetherGit** [comment]
Sure, i'll look into it.

**Comment by theetherGit** [comment]
@hallowatcher can you please tell me with manager you are using?

**Comment by hallowatcher** [comment]
@theetherGit im using Another Redis Desktop Manager (https://github.com/qishibo/AnotherRedisDesktopManager) and as Provider im using ioredis, but I would assume the same happens with the regular redis provider as the lines of code are the same.

**Comment by theetherGit** [comment]
Sorry, I literally made a big mistake. New version will be released with examples by midnight.
