### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by irt-msummers** [etherCorps/SK-Redis-SessionManager#5]
The demo is broken -- I can't seem to login on your vercel app.  Along with that do you have an example of your session.ts to use the upstash/redis on vercel.  I can't seem to figure that out.  Thanks

**Comment by theetherGit** [comment]
OK, For the broken demo i fixed it. ioredis session now needs to have `rediss://url`.

I'll add a demo of upstash.

**Comment by theetherGit** [comment]
you are using upstash redis with with `upstash redis` package or ioredis or node-redis??

**Comment by irt-msummers** [comment]
So I have my project working locally with your SK-Redis-SessionManager and it works great.  I was using ioredis.  I wanted to try out deploying to Vercel so I had to use upstash.  So right now I am using @upstash/redis and its getting confused -- it show connected but then it looks like its using the [ioredis] and getting an error using localhost.  My environment variables look correct on vercel and locally.

**Comment by theetherGit** [comment]
ok, got it. so in Node Js we have three libraries for redis 
1. ioredis
2. redis
3. @upstash/redis

- `ioredis` and `redis` both are built for NodeJs runtime and `@upstash/redis` based on rest api. 

As every package have some of there own api's and concepts i have provided session store for all three libraries.

So it depends on which library you are using with session manager. If you are using Vercel not vercel-edge then use ioredis. If you are using `@upstash/redis` library then use `upstashSessionStore`. 

When you are using redis provided by `upstash` with `redis` or `ioredis` please use redis url with `rediss://user:password@endpoint:port`. As you can see i'm using secure redis `rediss` not `redis`.

If you are using `@upstash/redis` and `upstashSessionStore`. You can try i'll add an example for it, eworking on it if i'll find an issue with this i'll update the package.

**Comment by irt-msummers** [comment]
Thanks so much for the info.  So you are saying I don't need to use upstash -- is it Vercel KV that I need to use instead or what -- I would really just like to use the ioredis library.  I looked at KV and it seem like you need to install @vercel/kv

**Comment by theetherGit** [comment]
Just use ioredis.

**Comment by theetherGit** [comment]
With this all the issues i found with @upstash/redis are fixed. You can open a discussion for guide.
